spring.datasource.url=jdbc:mysql://localhost:3306/callyAI?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

# DeepSeek
deepseek.api.key=NELEIDO_PUSHINT_GO_ADD_MANUALLY
deepseek.api.url=https://api.deepseek.com/chat/completions
deepseek.model=deepseek-chat

# GPT-4o
gpt4o.api.key=NELEIDO_PUSHINT_GO_ADD_MANUALLY
gpt4o.api.url=https://api.openai.com/v1/chat/completions
gpt4o.model=gpt-4o-mini